version: '3.8'
services:
  backend:
    build:
      context: ../backend
    container_name: bhavyan_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/bhavyan_tutorials
      - JWT_SECRET=your_jwt_secret_here
    depends_on:
      - mongo
    volumes:
      - ../backend/uploads:/usr/src/app/uploads
