version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/carrykaro

  frontend:
    image: nginx:alpine
    ports:
      - 3000:80
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - backend

volumes:
  mongo-data:
